### ISSUE TITLE
DEPRECATED: Using ranges of the form [begin:end] with begin value greater than the end value is deprecated in pathbuilder.scad, line 673 

### ISSUE THREAD

**Issue by 3Dietrich** [dinther/pathbuilder#10]
I used the latest version (Sep 30) of pathbuilder.
I build something in Inkscape and wanted to extrude it in OpenSCAD. But there is an error when svgShape()ing it:
`DEPRECATED: Using ranges of the form [begin:end] with begin value greater than the end value is deprecated in file ../../../../../OpenSCAD/libraries/pathbuilder.scad, line 673 `

[attached](https://github.com/dinther/pathbuilder/files/7271819/Towelclip_v2.zip) is the svg, 3 layers, one for each form.
[attached](https://github.com/dinther/pathbuilder/files/7271819/Towelclip_v2.zip) is the scad file, using the Inkscape/XML Editor/path content as "form1", "form2" and "betwn"

In scad I let "svgShape()" each form, but only the (simplest) "betwn" gets rendered. "form1" and "form2" get Deprecated..

Attachment: [Towelclip_v2.zip](https://github.com/dinther/pathbuilder/files/7271819/Towelclip_v2.zip)

**Comment by dinther** [comment]
Thanks Dietrich, I have a look at it now.

**Comment by dinther** [comment]
Found it. 1 segment arcs failed. In that case a straight line should be drawn. Fixed the code and it produced this:

![image](https://user-images.githubusercontent.com/1192916/135729966-42c9fc1b-1534-423c-b168-ef0992df7835.png)

Code fix is in the current file [pathbuilder.scad](https://github.com/dinther/pathbuilder/blob/main/pathbuilder.scad) file

**Comment by 3Dietrich** [comment]
great!

**Comment by 3Dietrich** [comment]
hmm .. what is now the problem?
[TowelClip_v2_2.zip](https://github.com/dinther/pathbuilder/files/7272233/TowelClip_v2_2.zip)

**Comment by dinther** [comment]
Do you see this error message in the console?

```
ERROR: Assertion '((rx * 2) >= d)' failed: "Radius:1.25 is too small for distance:2.50011" in file ../pathbuilder.scad, line 426 
```

You are asking to have an arc drawn of 1.25 radius over a span that is greater than two times the radius (2.50011 as in the error message)

**Comment by 3Dietrich** [comment]
yes. ok, that seems a difficult form. But could you open the svg? There is it, normal visible..

**Comment by 3Dietrich** [comment]
I found 2 (too close?) points, cleaned the forms. But there is again something bad in form2.
For comparison I added the exported svg forms with an extra scad, so you have both import svg and the same forms in pathbuilderForm.scad:
[pathbuilder_problems_3.zip](https://github.com/dinther/pathbuilder/files/7273115/pathbuilder_problems_3.zip)

**Comment by 3Dietrich** [comment]
> Do you see this error message in the console?

Yes, but I don't know where it is in inkscape - it looked good there.

But this is off topic.
So thank you for the fix!
