### ISSUE TITLE
different positions

### ISSUE THREAD

**Issue by 3Dietrich** [dinther/pathbuilder#12]
I started again with a new version of the brackets. One side is:
<img width="597" alt="Bildschirmfoto 2021-10-04 um 21 42 21" src="https://user-images.githubusercontent.com/4608796/135914198-f57609ef-afac-4a5c-bab8-14eece21d6a5.png">

and just tried the form to render via pathbuilder:
<img width="567" alt="Bildschirmfoto 2021-10-04 um 21 31 14" src="https://user-images.githubusercontent.com/4608796/135913795-c37d52eb-25da-4326-af0a-7894aa298a83.png">
**The problem:**

- special here: it looks very different, it seems that the 'teeth' and some points around it are offset
- allways: it's mirrored at the x-axis

.
some notes what happened in inkscape (beside a lot of point edits):
- The offset 'jagged' line is a shape that I cut out at the round rougher base shape (via 'Difference'). 
- I have moved everything (because of searching the unknown 0,0 starting point)

after finishing the form design I copied the inkscape/xml/d content and pasted it into the variable "f1" (and f2, f1hole, f2betw).
[here is .svg and .scad](https://github.com/dinther/pathbuilder/files/7280934/straightline_position.zip)

**Comment by dinther** [comment]
Thanks for that report. I found a major bug that caused longer sequences of numbers to be misinterpreted. That was the case for all curve types. This is now fixed.

However, another issue that needs fixing is that the program currently can not handle scientific notation in the string format. In command format there is no problem.

In your example code the variable f1 contains scientific notation. Just replace "-7.9e-5" with "-0.000079" With the updated pathbuilder f1 will render correctly. The other problem you reported earlier still exists.
