### ISSUE TITLE
errors in later versions of Openscad

### ISSUE THREAD

**Issue by bdad2** [dinther/pathbuilder#14]
using OpenSCAD 2022.11.18.ci12805 I'm getting a few issues. 
there are a couple of sequential commas (line 73, iirc)
and also in line 618  (and also elsewhere) it doesn't like n=$pb_spline. I set  n=10, and it now seems to run., but running into the non closed polygon issues mentioned previously.

Maybe it runs fine on other versions of Openscad.

**Comment by dinther** [comment]
Took me some time to realize there are dev versions of openSCAD. I did some work on the library and ran the examples on the latest dev version 2023.08.08 and everything seems to work fine.
